apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DB_USER: {{ .Values.appSecret.dbUser | b64enc | quote }}
  DB_PASSWORD: {{ .Values.appSecret.dbPassword | b64enc | quote }}
  DB_ROOT_PASSWORD: {{ .Values.appSecret.dbRootPassword | b64enc | quote }}