name: Deploy to Ionos VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Quizz
    steps:
      - name: Connexion SSH et Déploiement
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          script: |
            set -e
            cd /var/www/html/QuizzYnov
            git pull origin main

            # 3. Mise à jour des dépendances
            npm install --include=dev
            cd backend
            npm install
            cd ../frontend
            npm install
            cd ..

            # 4. Redémarrage (ou premier démarrage) PM2 en mode concurrently
            if pm2 describe quizzynov > /dev/null 2>&1; then
              pm2 restart quizzynov --update-env
            else
              pm2 start npm --name quizzynov --cwd /var/www/html/QuizzYnov -- run dev
            fi
            pm2 save
